export default {
  ONBOARDING: 'ONBOARDING',
  ONBOARDING_ONE: 'ONBOARDING_ONE',
  AUTH: 'AUTH',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  APP: 'APP',
  HOMESCREEN: 'HOMESCREEN',
  CATEGORIES: 'CATEGORIES',
  NOTIFICATIONS: 'NOTIFICATIONS',
  ORDERS_IN_PROGRESS: 'ORDERS_IN_PROGRESS',
};
